from .web_movingAverages_sma_ema import MovingAverageCrossStrategy
from .web_movingAvg_0 import ST_Trading_signals
from .web_supportResistance import The_Support_Resistance
from .web_overBought_overSold import The_OverBought_OverSold
from .optimal_double_sma import The_Strategy_2
from .runRun import runRun
from .optimal_sma import Optimal_SMA