from .web_backtrader_sma_strategy import backtrader_sma_strategy_run
from .web_one import Web_One
from .web_movingAverages_sma_ema import MovingAverageCrossStrategy
from .web_movingAvg_0 import ST_Trading_signals
from .web_supportResistance import The_Support_Resistance
from .web_overBought_overSold import The_OverBought_OverSold