from .web_movingAverages_sma_ema import MovingAverageCrossStrategy
from .web_supportResistance import The_Support_Resistance
from .web_overBought_overSold import The_OverBought_OverSold
from .optimal_double_sma import The_Strategy_2
from .trading_technicals import trading_technicals
from .optimal_sma import Optimal_SMA