[theme]
primaryColor="#767d74"
backgroundColor="#bbb9b9"
secondaryBackgroundColor="#506450"
textColor="#000000"
font="sans serif"


#[theme]
#primaryColor = "#d33682"
#backgroundColor = "#002b36"
#secondaryBackgroundColor = "#586e75"
#textColor = "#fafafa"
#font = "sans serif"


#[theme]
#primaryColor = "#575fe8"
#backgroundColor = "#f5f7f3"
#secondaryBackgroundColor = "#c9eab8"
#textColor = "#262730"
#font = "sans serif"


#[theme]
#primaryColor = "#E694FF"
#backgroundColor = "#00172B"
#secondaryBackgroundColor = "#0083B8"
#textColor = "#C6CDD4"
#font = "sans-serif"


# [theme]
# primaryColor="#bf210e"
# backgroundColor="#8e787d"
# secondaryBackgroundColor="#c1c1ce"
# textColor="#000000"
# font="sans serif"